function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 28-Sep-2016 19:59:37

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N     = 5;    % Order
    % Fpass = 8;    % Passband Frequency
    % Apass = 1;    % Passband Ripple (dB)
    % Fs    = 500;  % Sampling Frequency
    %
    % h = fdesign.lowpass('n,fp,ap', N, Fpass, Apass, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.97231141721311 0.982202871807817; 1 2 1 1 ...
        -1.9497629809793 0.954004431149146; 1 1 0 1 -0.971290538087342 0], ...
        'ScaleValues', [0.00247286364867692; 0.00106036254246188; ...
        0.0143547309563291; 1]);
end

s = double(x);
y = step(Hd,s);

